// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZeroFat.NutriPlan.Infrastructure.Persistence.Context;

#nullable disable

namespace Migrators.PostgreSQL.Migrations.NutriPlan
{
    [DbContext(typeof(NutriPlanContext))]
    [Migration("20250803171326_workingOnCustomMeal")]
    partial class workingOnCustomMeal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.CustomMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BaseMealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<string>("SpecialInstructions")
                        .HasColumnType("text");

                    b.Property<double>("TotalCalories")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalCarbs")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalFat")
                        .HasColumnType("double precision");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<double>("TotalProtein")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BaseMealId");

                    b.ToTable("CustomMeals", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.CustomMealOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomMealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomMealId");

                    b.HasIndex("OptionId");

                    b.ToTable("CustomMealOptions", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.Extra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrginalIngredientId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<double>("WeightInGrams")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MealId");

                    b.ToTable("Extras", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AddedVitaminB12")
                        .HasColumnType("double precision");

                    b.Property<double>("AddedVitaminE")
                        .HasColumnType("double precision");

                    b.Property<double>("Alcohol")
                        .HasColumnType("double precision");

                    b.Property<int>("BasicUnit")
                        .HasColumnType("integer");

                    b.Property<double>("Caffeine")
                        .HasColumnType("double precision");

                    b.Property<double>("CalciumPer100Unit")
                        .HasColumnType("double precision");

                    b.Property<double>("CaloriesPer100Unit")
                        .HasColumnType("double precision");

                    b.Property<int>("CaloriesUnit")
                        .HasColumnType("integer");

                    b.Property<double>("CarbsPer100Unit")
                        .HasColumnType("double precision");

                    b.Property<double>("CaroteneAlpha")
                        .HasColumnType("double precision");

                    b.Property<double>("CaroteneBeta")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<double>("CholesterolPer100Unit")
                        .HasColumnType("double precision");

                    b.Property<double>("Choline")
                        .HasColumnType("double precision");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<double>("CopperPer100Unit")
                        .HasColumnType("double precision");

                    b.Property<decimal>("CostPer100Unit")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CryptoxanthinBeta")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Density")
                        .HasColumnType("double precision");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text");

                    b.Property<int>("DietaryPreference")
                        .HasColumnType("integer");

                    b.Property<double>("FatPer100Unit")
                        .HasColumnType("double precision");

                    b.Property<double>("FiberPer100Unit")
                        .HasColumnType("double precision");

                    b.Property<double>("FolateDFE")
                        .HasColumnType("double precision");

                    b.Property<double>("FolateFood")
                        .HasColumnType("double precision");

                    b.Property<double>("FolateTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("FolicAcid")
                        .HasColumnType("double precision");

                    b.Property<int>("IngredientSource")
                        .HasColumnType("integer");

                    b.Property<double>("IronPer100Unit")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDairyFree")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGlutenFree")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLowGI")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOrganic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSeasonal")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("LuteinZeaxanthin")
                        .HasColumnType("double precision");

                    b.Property<double>("Lycopene")
                        .HasColumnType("double precision");

                    b.Property<double>("MagnesiumPer100Unit")
                        .HasColumnType("double precision");

                    b.Property<double>("MonounsaturatedFattyAcid16_1")
                        .HasColumnType("double precision");

                    b.Property<double>("MonounsaturatedFattyAcid18_1")
                        .HasColumnType("double precision");

                    b.Property<double>("MonounsaturatedFattyAcid20_1")
                        .HasColumnType("double precision");

                    b.Property<double>("MonounsaturatedFattyAcid22_1")
                        .HasColumnType("double precision");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<double>("Niacin")
                        .HasColumnType("double precision");

                    b.Property<double>("PhosphorusPer100Unit")
                        .HasColumnType("double precision");

                    b.Property<double>("PolyunsaturatedFattyAcid18_2")
                        .HasColumnType("double precision");

                    b.Property<double>("PolyunsaturatedFattyAcid18_3")
                        .HasColumnType("double precision");

                    b.Property<double>("PolyunsaturatedFattyAcid18_4")
                        .HasColumnType("double precision");

                    b.Property<double>("PolyunsaturatedFattyAcid20_4")
                        .HasColumnType("double precision");

                    b.Property<double>("PolyunsaturatedFattyAcid20_5")
                        .HasColumnType("double precision");

                    b.Property<double>("PolyunsaturatedFattyAcid22_5")
                        .HasColumnType("double precision");

                    b.Property<double>("PolyunsaturatedFattyAcid22_6")
                        .HasColumnType("double precision");

                    b.Property<double>("PotassiumPer100Unit")
                        .HasColumnType("double precision");

                    b.Property<double>("ProteinPer100Unit")
                        .HasColumnType("double precision");

                    b.Property<double>("Retinol")
                        .HasColumnType("double precision");

                    b.Property<double>("Riboflavin")
                        .HasColumnType("double precision");

                    b.Property<double>("SaturatedFattyAcid10_0")
                        .HasColumnType("double precision");

                    b.Property<double>("SaturatedFattyAcid12_0")
                        .HasColumnType("double precision");

                    b.Property<double>("SaturatedFattyAcid14_0")
                        .HasColumnType("double precision");

                    b.Property<double>("SaturatedFattyAcid16_0")
                        .HasColumnType("double precision");

                    b.Property<double>("SaturatedFattyAcid18_0")
                        .HasColumnType("double precision");

                    b.Property<double>("SaturatedFattyAcid4_0")
                        .HasColumnType("double precision");

                    b.Property<double>("SaturatedFattyAcid6_0")
                        .HasColumnType("double precision");

                    b.Property<double>("SaturatedFattyAcid8_0")
                        .HasColumnType("double precision");

                    b.Property<double>("SeleniumPer100Unit")
                        .HasColumnType("double precision");

                    b.Property<double>("SodiumPer100Unit")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StorageInstructionsAr")
                        .HasColumnType("text");

                    b.Property<string>("StorageInstructionsEn")
                        .HasColumnType("text");

                    b.Property<double>("SugarPer100Unit")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<double>("Theobromine")
                        .HasColumnType("double precision");

                    b.Property<double>("Thiamin")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalMonounsaturatedFattyAcids")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalPolyunsaturatedFattyAcids")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalSaturatedFattyAcids")
                        .HasColumnType("double precision");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<double>("VitaminARAE")
                        .HasColumnType("double precision");

                    b.Property<double>("VitaminB12")
                        .HasColumnType("double precision");

                    b.Property<double>("VitaminB6")
                        .HasColumnType("double precision");

                    b.Property<double>("VitaminC")
                        .HasColumnType("double precision");

                    b.Property<double>("VitaminD")
                        .HasColumnType("double precision");

                    b.Property<double>("VitaminE")
                        .HasColumnType("double precision");

                    b.Property<double>("VitaminK")
                        .HasColumnType("double precision");

                    b.Property<double>("WaterPer100g")
                        .HasColumnType("double precision");

                    b.Property<double>("ZincPer100Unit")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Ingredients", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.IngredientAllergen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AllergenId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IngredientId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AllergenId");

                    b.HasIndex("IngredientId");

                    b.ToTable("IngredientAllergens", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.IngredientAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NutrientsAttributeId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("NutrientsAttributeId");

                    b.ToTable("IngredientAttributes", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.IngredientMeasurementUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<double>("EquivalentInUnit")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MeasurementUnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MeasurementUnitId");

                    b.ToTable("IngredientMeasurementUnits", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivationChangedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivationChangedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ActivationChangedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double>("Carbs")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Cuisine")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<int[]>("DietaryCategories")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<double>("Fat")
                        .HasColumnType("double precision");

                    b.Property<string>("FullRecipeTextAr")
                        .HasColumnType("text");

                    b.Property<string>("FullRecipeTextEn")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAddOn")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCold")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDairyFree")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGlutenFree")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLowGI")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWarm")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrginalMealId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreparationMethodAr")
                        .HasColumnType("text");

                    b.Property<string>("PreparationMethodEn")
                        .HasColumnType("text");

                    b.Property<double>("PriceForCustomer")
                        .HasColumnType("double precision");

                    b.Property<double>("Protein")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SuitableForFreezing")
                        .HasColumnType("boolean");

                    b.Property<double>("Water")
                        .HasColumnType("double precision");

                    b.Property<double>("WeightInGrams")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Meals", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.MealAllergen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AllergenId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MealId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AllergenId");

                    b.HasIndex("MealId");

                    b.ToTable("MealAllergens", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.MealCustomizationGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CaloriesAdjustment")
                        .HasColumnType("double precision");

                    b.Property<double>("CarbsAdjustment")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<double>("FatAdjustment")
                        .HasColumnType("double precision");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxSelection")
                        .HasColumnType("integer");

                    b.Property<int>("MinSelection")
                        .HasColumnType("integer");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<double>("ProteinAdjustment")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("MealCustomizationGroups", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.MealCustomizationOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CaloriesAdjustment")
                        .HasColumnType("double precision");

                    b.Property<double>("CarbsAdjustment")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FatAdjustment")
                        .HasColumnType("double precision");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MealId")
                        .HasColumnType("uuid");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<decimal>("PriceAdjustment")
                        .HasColumnType("numeric");

                    b.Property<double>("ProteinAdjustment")
                        .HasColumnType("double precision");

                    b.Property<string>("ReplacesComponent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MealId");

                    b.ToTable("MealCustomizationOptions", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double>("Carbs")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("CookingTime")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Cuisine")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<int[]>("DietaryCategories")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<double>("Fat")
                        .HasColumnType("double precision");

                    b.Property<string>("FullRecipeTextAr")
                        .HasColumnType("text");

                    b.Property<string>("FullRecipeTextEn")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsCold")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDairyFree")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGlutenFree")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLowGI")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWarm")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<string>("PreparationMethodAr")
                        .HasColumnType("text");

                    b.Property<string>("PreparationMethodEn")
                        .HasColumnType("text");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("integer");

                    b.Property<double>("Protein")
                        .HasColumnType("double precision");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<double>("Water")
                        .HasColumnType("double precision");

                    b.Property<double>("WeightInGrams")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Recipes", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<int>("BasicUnit")
                        .HasColumnType("integer");

                    b.Property<bool>("HideOnCustomerPorter")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean");

                    b.Property<string>("MeasurementUnitCode")
                        .HasColumnType("text");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<double>("WeightInGrams")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.RecipeMealType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MealTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeMealTypes", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MenuPlanning.DailyMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AverageCalories")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MealPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MealTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("MealPlanId");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("MenuId");

                    b.ToTable("DailyMenus", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MenuPlanning.DailyMenuMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DailyMenuId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MealId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DailyMenuId");

                    b.HasIndex("MealId");

                    b.ToTable("DailyMenuMeals", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MenuPlanning.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Menus", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.Settings.Allergen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Allergens", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.Settings.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CategoryType")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.Settings.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivationChangedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivationChangedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ActivationChangedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CarbPercentage")
                        .HasColumnType("numeric");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultDietitianGoal")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text");

                    b.Property<decimal?>("FatPercentage")
                        .HasColumnType("numeric");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Images")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<decimal?>("ProteinPercentage")
                        .HasColumnType("numeric");

                    b.Property<string>("StripeId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MealPlans", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.Settings.MealPlanMealType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AverageCalories")
                        .HasColumnType("numeric");

                    b.Property<Guid>("MealPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MealTypeId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId");

                    b.HasIndex("MealTypeId");

                    b.ToTable("MealPlanMealTypes", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.Settings.MealType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivationChangedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivationChangedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ActivationChangedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int?>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("ScheduledTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("MealTypes", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.Settings.MeasurementUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MeasurementUnits", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.Settings.NutrientsAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NutrientsAttributes", "NutriPlan");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.CustomMeal", b =>
                {
                    b.HasOne("ZeroFat.NutriPlan.Domain.MealPlanning.Meal", "BaseMeal")
                        .WithMany()
                        .HasForeignKey("BaseMealId");

                    b.Navigation("BaseMeal");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.CustomMealOption", b =>
                {
                    b.HasOne("ZeroFat.NutriPlan.Domain.MealPlanning.CustomMeal", "CustomMeal")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("CustomMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZeroFat.NutriPlan.Domain.MealPlanning.MealCustomizationOption", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomMeal");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.Extra", b =>
                {
                    b.HasOne("ZeroFat.NutriPlan.Domain.MealPlanning.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId");

                    b.HasOne("ZeroFat.NutriPlan.Domain.MealPlanning.Meal", "Meal")
                        .WithMany("Extras")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.Ingredient", b =>
                {
                    b.HasOne("ZeroFat.NutriPlan.Domain.Settings.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.IngredientAllergen", b =>
                {
                    b.HasOne("ZeroFat.NutriPlan.Domain.Settings.Allergen", "Allergen")
                        .WithMany("IngredientAllergens")
                        .HasForeignKey("AllergenId");

                    b.HasOne("ZeroFat.NutriPlan.Domain.MealPlanning.Ingredient", "Ingredient")
                        .WithMany("IngredientAllergens")
                        .HasForeignKey("IngredientId");

                    b.Navigation("Allergen");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.IngredientAttribute", b =>
                {
                    b.HasOne("ZeroFat.NutriPlan.Domain.MealPlanning.Ingredient", "Ingredient")
                        .WithMany("Attributes")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZeroFat.NutriPlan.Domain.Settings.NutrientsAttribute", "NutrientsAttribute")
                        .WithMany()
                        .HasForeignKey("NutrientsAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("NutrientsAttribute");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.IngredientMeasurementUnit", b =>
                {
                    b.HasOne("ZeroFat.NutriPlan.Domain.MealPlanning.Ingredient", "Ingredient")
                        .WithMany("IngredientMeasurementUnits")
                        .HasForeignKey("IngredientId");

                    b.HasOne("ZeroFat.NutriPlan.Domain.Settings.MeasurementUnit", null)
                        .WithMany("IngredientMeasurementUnits")
                        .HasForeignKey("MeasurementUnitId");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.Meal", b =>
                {
                    b.HasOne("ZeroFat.NutriPlan.Domain.MealPlanning.Recipe", "Recipe")
                        .WithMany("Meals")
                        .HasForeignKey("RecipeId");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.MealAllergen", b =>
                {
                    b.HasOne("ZeroFat.NutriPlan.Domain.Settings.Allergen", "Allergen")
                        .WithMany()
                        .HasForeignKey("AllergenId");

                    b.HasOne("ZeroFat.NutriPlan.Domain.MealPlanning.Meal", "Meal")
                        .WithMany("Allergens")
                        .HasForeignKey("MealId");

                    b.Navigation("Allergen");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.MealCustomizationOption", b =>
                {
                    b.HasOne("ZeroFat.NutriPlan.Domain.MealPlanning.MealCustomizationGroup", "Group")
                        .WithMany("Options")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZeroFat.NutriPlan.Domain.MealPlanning.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZeroFat.NutriPlan.Domain.MealPlanning.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId");

                    b.Navigation("Group");

                    b.Navigation("Ingredient");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.Recipe", b =>
                {
                    b.HasOne("ZeroFat.NutriPlan.Domain.Settings.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.RecipeIngredient", b =>
                {
                    b.HasOne("ZeroFat.NutriPlan.Domain.MealPlanning.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZeroFat.NutriPlan.Domain.MealPlanning.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.RecipeMealType", b =>
                {
                    b.HasOne("ZeroFat.NutriPlan.Domain.Settings.MealType", "MealType")
                        .WithMany()
                        .HasForeignKey("MealTypeId");

                    b.HasOne("ZeroFat.NutriPlan.Domain.MealPlanning.Recipe", "Recipe")
                        .WithMany("RecipeMealTypes")
                        .HasForeignKey("RecipeId");

                    b.Navigation("MealType");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MenuPlanning.DailyMenu", b =>
                {
                    b.HasOne("ZeroFat.NutriPlan.Domain.Settings.MealPlan", "MealPlan")
                        .WithMany()
                        .HasForeignKey("MealPlanId");

                    b.HasOne("ZeroFat.NutriPlan.Domain.Settings.MealType", "MealType")
                        .WithMany()
                        .HasForeignKey("MealTypeId");

                    b.HasOne("ZeroFat.NutriPlan.Domain.MenuPlanning.Menu", "Menu")
                        .WithMany("DailyMenus")
                        .HasForeignKey("MenuId");

                    b.Navigation("MealPlan");

                    b.Navigation("MealType");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MenuPlanning.DailyMenuMeal", b =>
                {
                    b.HasOne("ZeroFat.NutriPlan.Domain.MenuPlanning.DailyMenu", "DailyMenu")
                        .WithMany("Meals")
                        .HasForeignKey("DailyMenuId");

                    b.HasOne("ZeroFat.NutriPlan.Domain.MealPlanning.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId");

                    b.Navigation("DailyMenu");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.Settings.MealPlanMealType", b =>
                {
                    b.HasOne("ZeroFat.NutriPlan.Domain.Settings.MealPlan", "MealPlan")
                        .WithMany("MealPlanMealTypes")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZeroFat.NutriPlan.Domain.Settings.MealType", "MealType")
                        .WithMany("MealPlanMealTypes")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");

                    b.Navigation("MealType");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.CustomMeal", b =>
                {
                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.Ingredient", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("IngredientAllergens");

                    b.Navigation("IngredientMeasurementUnits");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.Meal", b =>
                {
                    b.Navigation("Allergens");

                    b.Navigation("Extras");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.MealCustomizationGroup", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MealPlanning.Recipe", b =>
                {
                    b.Navigation("Meals");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("RecipeMealTypes");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MenuPlanning.DailyMenu", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.MenuPlanning.Menu", b =>
                {
                    b.Navigation("DailyMenus");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.Settings.Allergen", b =>
                {
                    b.Navigation("IngredientAllergens");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.Settings.MealPlan", b =>
                {
                    b.Navigation("MealPlanMealTypes");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.Settings.MealType", b =>
                {
                    b.Navigation("MealPlanMealTypes");
                });

            modelBuilder.Entity("ZeroFat.NutriPlan.Domain.Settings.MeasurementUnit", b =>
                {
                    b.Navigation("IngredientMeasurementUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
